FROM node:18

RUN npm install -g nodemon
RUN npm install -g ts-node

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 8082

CMD ["nodemon", "--exec", "ts-node", "./app.ts"]