import { EditorLanguageEnum } from '../types/code/languages';

export const editorLanguageToFileExtensionMap: Record<EditorLanguageEnum, string> = {
  [EditorLanguageEnum.javascript]: 'js',
  [EditorLanguageEnum.typescript]: 'ts',
  [EditorLanguageEnum.python]: 'py',
  [EditorLanguageEnum.java]: 'java',
  [EditorLanguageEnum.c]: 'c',
  [EditorLanguageEnum.cpp]: 'cpp',
  [EditorLanguageEnum.bat]: 'bat',
  [EditorLanguageEnum.clojure]: 'clj',
  [EditorLanguageEnum.css]: 'css',
  [EditorLanguageEnum.csharp]: 'cs',
  [EditorLanguageEnum.dart]: 'dart',
  [EditorLanguageEnum.dockerfile]: '',
  [EditorLanguageEnum.elixir]: 'ex',
  [EditorLanguageEnum.fsharp]: 'fs',
  [EditorLanguageEnum.go]: 'go',
  [EditorLanguageEnum.graphql]: 'graphql',
  [EditorLanguageEnum.json]: 'json',
  [EditorLanguageEnum.julia]: 'jl',
  [EditorLanguageEnum.kotlin]: 'kt',
  [EditorLanguageEnum.lua]: 'lua',
  [EditorLanguageEnum.markdown]: 'md',
  [EditorLanguageEnum.mysql]: 'sql',
  [EditorLanguageEnum.objectivec]: 'm',
  [EditorLanguageEnum.pascal]: 'pas',
  [EditorLanguageEnum.perl]: 'pl',
  [EditorLanguageEnum.php]: 'php',
  [EditorLanguageEnum.text]: 'txt',
  [EditorLanguageEnum.pgsql]: 'psql',
  [EditorLanguageEnum.powerquery]: 'mez',
  [EditorLanguageEnum.powershell]: 'ps1',
  [EditorLanguageEnum.r]: 'r',
  [EditorLanguageEnum.ruby]: 'rb',
  [EditorLanguageEnum.rust]: 'rs',
  [EditorLanguageEnum.scala]: 'sc',
  [EditorLanguageEnum.sql]: 'sql',
  [EditorLanguageEnum.swift]: 'swift',
};

export const editorLanguageToAcceptedFileExtensionMap: Record<EditorLanguageEnum, string> = {
  [EditorLanguageEnum.javascript]: '.js',
  [EditorLanguageEnum.typescript]: '.ts, .js',
  [EditorLanguageEnum.python]: '.py',
  [EditorLanguageEnum.java]: '.java',
  [EditorLanguageEnum.c]: '.c',
  [EditorLanguageEnum.cpp]: '.cpp',
  [EditorLanguageEnum.bat]: '.bat',
  [EditorLanguageEnum.clojure]: '.clj, .cljs, .cljc, .edn',
  [EditorLanguageEnum.css]: '.css',
  [EditorLanguageEnum.csharp]: '.cs',
  [EditorLanguageEnum.dart]: '.dart',
  [EditorLanguageEnum.dockerfile]: '*',
  [EditorLanguageEnum.elixir]: '.ex',
  [EditorLanguageEnum.fsharp]: '.fs',
  [EditorLanguageEnum.go]: '.go',
  [EditorLanguageEnum.graphql]: '.graphql',
  [EditorLanguageEnum.json]: '.json',
  [EditorLanguageEnum.julia]: '.jl',
  [EditorLanguageEnum.kotlin]: '.kt',
  [EditorLanguageEnum.lua]: '.lua',
  [EditorLanguageEnum.markdown]: '.md',
  [EditorLanguageEnum.mysql]: '.sql',
  [EditorLanguageEnum.objectivec]: '.m',
  [EditorLanguageEnum.pascal]: '.pas',
  [EditorLanguageEnum.perl]: '.pl',
  [EditorLanguageEnum.php]: '.php',
  [EditorLanguageEnum.text]: '.txt',
  [EditorLanguageEnum.pgsql]: '.psql, .sql',
  [EditorLanguageEnum.powerquery]: '.mez',
  [EditorLanguageEnum.powershell]: '.ps1',
  [EditorLanguageEnum.r]: '.r',
  [EditorLanguageEnum.ruby]: '.rb',
  [EditorLanguageEnum.rust]: '.rs',
  [EditorLanguageEnum.scala]: '.sc',
  [EditorLanguageEnum.sql]: '.sql',
  [EditorLanguageEnum.swift]: '.swift',
};
