name: Deploy frontend

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REACT_APP_BACKEND_URL: ${{ secrets.REACT_APP_BACKEND_URL }}
      REACT_APP_USER_SERVICE_BACKEND_URL: ${{ secrets.REACT_APP_USER_SERVICE_BACKEND_URL }}
      REACT_APP_COLLABORATION_SERVICE_BACKEND_URL: ${{ secrets.REACT_APP_COLLABORATION_SERVICE_BACKEND_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies and Build
        run: |
          cd frontend
          export NODE_OPTIONS="--max_old_space_size=4096"
          npm ci
          npm run build
